# Risk Register

```{r}
percent_tmap <- function(df, column, title) {
  col <- enquo(column)
  risk_category <- count(df, !!col) %>%
        mutate(percent = (n / sum(n)) * 100) %>%
        mutate(label = paste0(!!col, " (",
                              round(percent, 1), "%)"))
  p1 <- ggplot(risk_category, 
               aes(area = n, fill = label, label = label)) +
          geom_treemap() +
          geom_treemap_text(reflow = TRUE, min.size = 4, grow = FALSE) + 
          scale_fill_brewer(palette = "Dark2") +
          theme(legend.position = "none") +
          ggtitle(title)
  return(risk_category)
}
```

```{r}
percent_tmap(risk, "RISKCATEGORY", "Risk Categories")
```



## Summary Statistics
```{r, echo=FALSE, warning=FALSE, message=FALSE, out.width='100%'}
risk_category <- count(risk, RISKCATEGORY) %>%
        mutate(percent = (n / sum(n)) * 100) %>%
        mutate(label = paste0(RISKCATEGORY, " (",
                              round(percent, 1), "%)"))
p1 <- ggplot(risk_category, 
             aes(area = n, fill = label, label = label)) +
        geom_treemap() +
        geom_treemap_text(reflow = TRUE, min.size = 4, grow = FALSE) + 
        scale_fill_brewer(palette = "Dark2") +
        theme(legend.position = "none") +
        ggtitle("Risk Categories")

component <- count(risk, COMPONENT) %>%
        mutate(percent = (n / sum(n)) * 100) %>%
        mutate(label = paste0(COMPONENT, " (",
                              round(percent, 1), "%)"))
p2 <- ggplot(component, 
             aes(area = n, fill = COMPONENT, label = label)) +
        geom_treemap() +
        geom_treemap_text(reflow = TRUE, min.size = 4, grow = FALSE) + 
        scale_fill_brewer(palette = "Dark2") +
        theme(legend.position = "none") +
        ggtitle("Project Components")

risk_strategy <- count(risk, RISK_STRATEGY) %>%
        mutate(percent = (n / sum(n)) * 100) %>%
        mutate(label = paste0(RISK_STRATEGY, " (",
                              round(percent, 1), "%)"))
p3 <- ggplot(risk_strategy, 
             aes(area = n, fill = RISK_STRATEGY, label = label)) +
        geom_treemap() +
        geom_treemap_text(reflow = TRUE, min.size = 4, grow = FALSE) + 
        scale_fill_brewer(palette = "Dark2") +
        theme(legend.position = "none") +
        ggtitle("Risk Strategy")

timing_of_delay <- count(risk, TIMING_OF_DELAY) %>%
        mutate(percent = (n / sum(n)) * 100) %>%
        mutate(label = paste0(TIMING_OF_DELAY, " (",
                              round(percent, 1), "%)"))
p4 <- ggplot(timing_of_delay, 
             aes(area = n, fill = TIMING_OF_DELAY, label = label)) +
        geom_treemap() +
        geom_treemap_text(reflow = TRUE, min.size = 4, grow = FALSE) + 
        scale_fill_brewer(palette = "Dark2") +
        theme(legend.position = "none") +
        ggtitle("Timing of Delay")

grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)
```

## Risks
```{r risk-register-table, echo=FALSE, warning=FALSE, message=FALSE}
risk_register_table(risk)
```

## Related Actions

## Related Decisions

