# Acoustic Deterrent

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Filter for the current feature
acoustic_risk <- filter(risk, FEATURE == "Acoustic Fish Deterrent" | 
                              FEATURE == "All")
```

## Summary
```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=5, out.width='100%', fig.cap = paste0("Risk Characteristics (n = ", length(unique(acoustic_risk$RISK_NO)), ")")}
p1 <- rarr::percent_treemap(acoustic_risk, RISKCATEGORY, "Risk Categories")
p3 <- rarr::percent_treemap(acoustic_risk, RISK_STRATEGY, "Risk Strategy")
p4 <- rarr::percent_treemap(acoustic_risk, TIMING_OF_DELAY, "Timing of Delay")
p5 <- rarr::percent_treemap(acoustic_risk, DISCIPLINE, "Discpline")
grid.arrange(p1, p3, p4, p5, nrow = 2, ncol = 2)
```

## Risks
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Create the table
rarr::risk_register_table(acoustic_risk)
```

## Project Timeline
```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Project Timeline"}
rarr::timeline(risk_df = filter(risk_time, FEATURE == "Acoustic Fish Deterrent" | 
                                     FEATURE == "All"), 
         groups_df = risk_time_riskcategory,
         height = "700px",
         start = "2021-01-01",
         end = "2025-01-01")
```
