# POC Reports

```{r, echo=FALSE, warning=FALSE, message=FALSE}
pocs <- unique(risk$TECHNICAL_POC)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
for(poc in pocs) {
  # Create POC header
  rarr::pandoc_header(poc, level = 2, number = FALSE, list = TRUE)
  
  # Create Risk header
  poc_identifier <- str_replace_all(poc, "[ /]", "-")
  poc_identifier <- paste0(poc_identifier, "-risk-items")
  rarr::pandoc_header("Risk Items", level = 3, 
                identifier = poc_identifier,
                number = FALSE, list = FALSE)
  
  # Subset risks for the current POC
  poc_risk <- risk %>%
    filter(TECHNICAL_POC == poc)
  
  # Set the heading level for risk items
  risk_heading_level <- 4
  risk_identifier_prefix <- "poc-risk-item"
  list_risk_item <- FALSE
  
  # Iterate through risks and produce a risk-item-report for each risk.
  risk_item_reports <- lapply(poc_risk$risk_no, function(x) {
    knitr::knit_child("reports/risk-item-report.Rmd",
                      envir = environment(),
                      quiet = TRUE)
  })

  # Expand the list of risk reports
  cat(unlist(risk_item_reports), sep = '\n')

  # Add a page break
  cat(c("::: {.page-break}", ":::"), sep = '\n')
}
```
