--- 
title: "Brandon Road Interbasin Project Risk Analysis Report"
author: "USACE Rock Island District"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: "Report description goes here."
bibliography: [book.bib, packages.bib]
biblio-style: apalike
csl: chicago-fullnote-bibliography.csl
---

# Introduction {-}

## Project 
* P2 project name: Brandon Rd-Great Lakes/Miss Rvr Interbasin
* P2 project number: 482782
* P2 program code: 451617

<!-- Libraries -->
```{r library, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(rmarkdown)
library(lubridate)
library(tools)
library(kableExtra)
library(pander)
library(timevis)
library(treemapify)
library(gridExtra)
library(formattable)
```

```{r source, echo=FALSE, warning=FALSE, message=FALSE}
source("R/risk_register_table.R")
source("R/atx_header.R")
source("R/pandoc_header.R")
source("R/percent_treemap.R")
source("R/timeline.R")
```

<!-- chunk options -->
```{r chunk-opts, echo=FALSE, warning=FALSE, message=FALSE}
options(width = 60)

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE
  )
```

<!-- Report Constants -->
```{r, echo=FALSE, warning=FALSE, message=FALSE}
qa_email_address <- "Marisa.C.Lack@usace.army.mil"
```

<!-- Wrangle Data -->
```{r wrangle-risk, echo=FALSE, warning=FALSE, message=FALSE}
risk_oracle <- read_csv(file = "data/RR_MAIN_REPORT_VIEW_20211104.csv")

# Convert date character fields to POSIXct and format format for date
risk <- risk_oracle %>%
  mutate(start_date      = lubridate::dmy_hms(START_DATE)) %>%
  mutate(end_date        = lubridate::dmy_hms(END_DATE)) %>%
  mutate(level_date      = lubridate::dmy_hms(LEVEL_DATE)) %>%
  mutate(poc_review_date = lubridate::dmy_hms(POC_REVIEW_DATE))

# Rename fields
risk <- risk %>%
  rename(cost_risk_color = CONDITIONAL_FORMATTING) %>%
  rename(schedule_risk_color = CONDITIONAL_FORMATTING2)

# Set engagement level integer field
risk <- risk %>%
  mutate(eng_level = as.numeric(str_extract(ENG_LEVEL, "\\d")))

# Ensure colors are lowercase
risk$cost_risk_color     <- tolower(risk$cost_risk_color)
risk$schedule_risk_color <- tolower(risk$schedule_risk_color)

# Calculate efficacy_risk_color
risk$efficacy_risk_color <- recode(risk$EFFICACY_RISK,
                                   Low = "green",
                                   Moderate = "orange",
                                   High = "red")

# Add efficacy_impact_per_project
risk$EFFICACY_IMPACT_PER_PROJECT <- ""

# Convert factor variables to title case
risk$RISKCATEGORY <- toTitleCase(tolower(risk$RISKCATEGORY))

# Cleanup risk number for sorting
risk <- risk %>%
  mutate(risk_no_risk_cat_code = str_extract(RISK_NO, "\\w+\\b")) %>%
  mutate(risk_no_number_string = str_extract(RISK_NO, "\\b\\w+$")) %>%
  mutate(risk_no_number = str_extract(risk_no_number_string, "\\d+")) %>%
  mutate(risk_no_letter_na = str_extract(risk_no_number_string, "\\D+")) %>%
  mutate(risk_no_letter = replace_na(risk_no_letter_na,
                                     replace = "")) %>%
  mutate(risk_no_letter_lower = tolower(risk_no_letter)) %>%
  mutate(risk_no_padded = str_pad(risk_no_number, 
                                  width = 3, 
                                  side = "left",
                                  pad = "0")) %>%
  mutate(risk_no = str_c(risk_no_risk_cat_code, 
                          "-",
                          risk_no_padded,
                          risk_no_letter_lower))

# Remove unused fields
risk <- risk %>%
  select(!c(PDT_DISC_CONC, PDT_DISC_LIKELI_IMPACT,
            PDT_DISC_RISK_MANAG_STRATEGY, ACTION_ITEMS, LESSONS_LEARNED,
            START_DATE, END_DATE, LEVEL_DATE, POC_REVIEW_DATE, 
            FK_TABLE_ID,
            risk_no_number_string, risk_no_number,
            risk_no_letter_na, risk_no_letter_lower,
            risk_no_letter, risk_no_padded))

# Create hyperlink to Risk_No
risk <- risk %>%
  mutate(risk_no_link = paste0("[", risk$risk_no, "](#risk-item-", 
                               tolower(risk$risk_no), ")"))

# Reorder fields
risk <- risk %>%
  relocate(CONCERNS, .after = RISK_NO) %>%
  relocate(COST_RISK, .after = COST_IMPACT_PER_PROJECT) %>%
  relocate(cost_risk_color,  .after = COST_RISK) %>%
  relocate(SCHEDULE_RISK, .after = SCHEDULE_IMPACT_PER_PROJECT) %>%
  relocate(schedule_risk_color, .after = SCHEDULE_RISK) %>%
  relocate(EFFICACY_IMPACT, .after = EFFICACY_LIKELIHOOD) %>%
  relocate(EFFICACY_IMPACT_PER_PROJECT, .after = EFFICACY_IMPACT) %>%
  relocate(efficacy_risk_color, .after = EFFICACY_RISK) %>%
  relocate(TIMING_OF_DELAY, .after = RISK_STRATEGY) %>%
  relocate(start_date, .after = CONCERNS) %>%
  relocate(end_date, .after = start_date) %>%
  relocate(risk_no, .after = RISK_NO) %>%
  relocate(risk_no_link, .after = risk_no) %>%
  relocate(poc_review_date, .after = RESPONSIBLE_POC) %>%
  relocate(eng_level, .after = ENG_LEVEL)

# Remove duplicates and sort
risk <- risk %>%
  distinct(risk_no, .keep_all = TRUE) %>%
  arrange(risk_no)

# Cleanup
#rm(risk_oracle)
```

```{r wrangle-events, echo=FALSE, warning=FALSE, message=FALSE}
events_oracle <- read_csv(file = "data/EVENTS_EVW_20211104.csv")

# Set date fields
events <- events_oracle %>%
  mutate(level_date = dmy_hms(LEVEL_DATE)) %>%
  mutate(level_date = formattable(level_date, format = "%Y-%m-%d"))

# Set engagement level integer field
events <- events %>%
  mutate(eng_level = as.numeric(str_extract(ENG_LEVEL, "\\d")))

# Cleanup risk number for sorting
events <- events %>%
  mutate(fk_table_id_cat_code = str_extract(FK_TABLE_ID, "\\w+\\b")) %>%
  mutate(fk_table_id_number_string = str_extract(FK_TABLE_ID, "\\b\\w+$")) %>%
  mutate(fk_table_id_number = str_extract(fk_table_id_number_string, "\\d+")) %>%
  mutate(fk_table_id_letter_na = str_extract(fk_table_id_number_string, "\\D+")) %>%
  mutate(fk_table_id_letter = replace_na(fk_table_id_letter_na,
                                         replace = "")) %>%
  mutate(fk_table_id_letter_lower = tolower(fk_table_id_letter)) %>%
  mutate(fk_table_id_padded = str_pad(fk_table_id_number, 
                                      width = 3, 
                                      side = "left",
                                      pad = "0")) %>%
  mutate(fk_table_id = str_c(fk_table_id_cat_code, 
                             "-",
                             fk_table_id_padded,
                             fk_table_id_letter_lower))

# Remove unused fields
events <- events %>%
  select(!c(LEVEL_DATE, CREATED_USER, CREATED_DATE, 
            LAST_EDITED_USER, LAST_EDITED_DATE, 
            fk_table_id_cat_code, fk_table_id_number_string, fk_table_id_number,
            fk_table_id_letter_na, fk_table_id_letter_lower, 
            fk_table_id_letter, fk_table_id_padded))

# Reorder fields
events <- events %>%
  relocate(fk_table_id, .after = FK_TABLE_ID) %>%
  relocate(DESCRIPTION, .after = fk_table_id) %>%
  relocate(level_date, .after = ENG_LEVEL) %>%
  relocate(eng_level, .after = ENG_LEVEL)

# Sort
events <- events %>%
  arrange(TABLE_NAME, level_date)

# Cleanup
rm(events_oracle)
```

```{r wrangle-discussion, echo=FALSE, warning=FALSE, message=FALSE}
discussion_oracle <- read_csv(file = "data/R_DISC_LOG_MAIN_REPORT_VIEW_20211104.csv")

# Set date fields
discussion <- discussion_oracle %>%
  mutate(poc_review_date = lubridate::dmy_hms(POC_REVIEW_DATE))

discussion <- discussion %>%
  mutate(fk_table_id_cat_code = str_extract(FK_TABLE_ID, "\\w+\\b")) %>%
  mutate(fk_table_id_number_string = str_extract(FK_TABLE_ID, "\\b\\w+$")) %>%
  mutate(fk_table_id_number = str_extract(fk_table_id_number_string, "\\d+")) %>%
  mutate(fk_table_id_letter_na = str_extract(fk_table_id_number_string, "\\D+")) %>%
  mutate(fk_table_id_letter = replace_na(fk_table_id_letter_na,
                                         replace = "")) %>%
  mutate(fk_table_id_letter_lower = tolower(fk_table_id_letter)) %>%
  mutate(fk_table_id_padded = str_pad(fk_table_id_number, 
                                      width = 3, 
                                      side = "left",
                                      pad = "0")) %>%
  mutate(fk_table_id = str_c(fk_table_id_cat_code, 
                             "-",
                             fk_table_id_padded,
                             fk_table_id_letter_lower))

# Remove unused fields
discussion <- discussion %>%
  select(!c(POC_REVIEW_DATE,
            fk_table_id_cat_code, fk_table_id_number_string, fk_table_id_number,
            fk_table_id_letter_na, fk_table_id_letter, fk_table_id_letter_lower, 
            fk_table_id_padded))

# Reorder fields
discussion <- discussion %>%
  relocate(fk_table_id, .after = FK_TABLE_ID) %>%
  relocate(RESPONSIBLE_POC, .after = DISCUSSION) %>%
  relocate(poc_review_date, .after = RESPONSIBLE_POC)

# Cleanup
rm(discussion_oracle)
```

```{r create_timevis_df, echo=FALSE, warning=FALSE, message=FALSE}
# Create a timevis "data" data frame of risks
risk_time <- risk %>%
  arrange(risk_no) %>%
  select(OBJECTID, risk_no, start_date, end_date, risk_no_risk_cat_code, 
         CONCERNS, COMPONENT, RESPONSIBLE_POC, eng_level) %>%
  rename(id = OBJECTID) %>%
  rename(content = risk_no) %>%
  relocate(id, .before = content) %>%
  rename(start = start_date) %>%
  rename(end = end_date) %>%
  rename(title = CONCERNS) %>%
  relocate(title, .after = content) %>%
  mutate(group = as.numeric(factor(risk_no_risk_cat_code))) %>%
  relocate(group, .after = end)

# Create a timevis "group" data frame to group risks by unique Risk Categories
risk_time_riskcategory <- risk %>%
  select(risk_no_risk_cat_code, RISKCATEGORY) %>%
  mutate(id = as.numeric(factor(risk_no_risk_cat_code))) %>%
  rename(content = risk_no_risk_cat_code) %>%
  rename(title = RISKCATEGORY) %>%
  relocate(id, .before = content) %>%
  distinct(id, content, .keep_all = TRUE)
```

